/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

public class App {


    public static void main(String[] args) {
        System.out.println("Kafka Windowed TimeStream Analysis");
    }
}
